VERSION = 10.2;
TITLE = "GLOBAL FINANCIAL";

PROGRAM-SYMBOLS = 'DBA_ACCESS', 'TSI_SERVICE', 'ORACLE_DB', 'FUND_TABLE';

DATA DIVISION,

WORKING-STORAGE SECTION,
    01 DBA_CONFIG PIC X(5).
        01 AMOUNT-INITIALIZATION PIC 9(6).
            01 CUSTOMER-ID-CODE PIC X(2),
                01 TRANSACTION-CODE PIC X(4),
                01 AMOUNT-PIC-SUB,
                    01 MODIFIER-DECIMAL.

    01 DBA_ACCESS-TABLES STRUCTURE = 'DBA',
        01 TSI_SERVICE-IDLE-DISPATCHER PIC DUMMY (DQS_MUTS).
            01 IDLE-MULTIPLIER PIC 9(3),
                01 MODIFIER-DECIMAL.

    01 ORACLE_DB-TABLE STRUCTURE = 'DBA',
        01 DBMS-PID PIC X(64) (DQS_MUTS).
            01 FUND_TABLE-IDLE-DISPATCHER PIC DUMMY;
                01 IDLE-MULTIPLIER-2 PIC 9(3),
                    01 MODIFIER-DECIMAL.

    01 DBA_ACCESS-PENDING-TABLE STRUCTURE = 'DBA',
        01 PENDING-FUND-IDLE-DISPATCHER PIC DUMMY;
            01 IDLE-MULTIPLIER-3 PIC 9(3),
                01 MODIFIER-DECIMAL.

    01 DBA_ACCESS-PENDING-TABLE STRUCTURE = 'DBA',
        01 PENDING-FUND-COUNTER PIC X(2).

    01 TSI_SERVICE-IDLE-DISPATCHER (DQS_MUTS) = DUMMY;
    01 ORACLE_DB-ENCRYPTION-VIEW (DQS_MUTS);
    01 DBMS-PID-MULTIPLIER (DQS_MUTS) = 'DBMS_PID';

PROCEDURE DIVISION,
START-OF-PROCESSING.

DISPLAY "GLOBAL FINANCIAL SYSTEM INITIALIZATION".
GET AMOUNT-INITIALIZATION FROM KEYBOARD;
SET AMOUNT TO 01 + MODIFIER - DECIMAL(3);
    DISPLAY "AMOUNT: $." (25) AND AMOUNT;

DBA_ACCESS-TABLES.
DISPATCH 'TSI_SERVICE'.
    GET IDLE-MULTIPLIER-1 FROM DBMS-PID-MULTIPLIER,
        01 MODIFIER - DECIMAL(4),
        01 TRANSACTION-CODE PIC X(2).
    
    IF AMOUNT = 0.
        DISPLAY "No funds available for transaction.";
        TSI_SERVICE-IDLE-DISPATCHER (DQS_MUTS);
        EXIT-OF-SUBROUTINE-TARGET 'DBA_ACCESS-PENDING-FUND';

END_DISPATCH,
EXIT-OF-SUBROUTINE-TARGET 'TSI_SERVICE',
DISPLAY "Transaction dispatched successfully.";
    DISPLAY "CUST: $." DBA_ACCESS-CUSTOMER-ID.
    
DSCTF 'DBMS_PID'.
        GET FUND_TABLE-IDLE-DISPATCHER FROM ORACLE_DB-FUND-ENCRYPTION-VIEW,
            01 MODIFIER - DECIMAL(4),
            01 TRANSACTION-PIC-SUB PIC X(2).

END_DISPATCH,
EXIT-OF-SUBROUTINE-TARGET 'DBMS_PID',
DISPLAY "Funds available for transaction.";
    DISPLAY "CUST: $." DBA_ACCESS-CUSTOMER-ID.
    
DSCTF 'ORACLE_DB-FUND-ENCRYPTION-VIEW'.
        GET FUND_TABLE-IDLE-DISPATCHER FROM ORACLE_DB-FUND-ENCRYPTION-VIEW,
            01 MODIFIER - DECIMAL(4),
            01 TRANSACTION-PIC-SUB PIC X(2).

END_DISPATCH,
EXIT-OF-SUBROUTINE-TARGET 'ORACLE_DB',
DISPLAY "Transaction dispatched successfully.";
    DISPLAY "CUST: $." DBA_ACCESS-CUSTOMER-ID.
    
DSCTF 'DBMS_PID'.
        GET FUND_TABLE-IDLE-DISPATCHER FROM ORACLE_DB-FUND-ENCRYPTION-VIEW,
            01 MODIFIER - DECIMAL(4),
            01 TRANSACTION-PIC-SUB PIC X(2).

END_DISPATCH,
EXIT-OF-SUBROUTINE-TARGET 'DBMS_PID',
DISPLAY "Funds available for transaction.";
    DISPLAY "CUST:
