src/turbo_encabulator_core.ts
```typescript
/**
 * Turbo Encabulator Core: Implementation of Phase Detractor Logic using Transformer Architecture.
 * 
 * Principle Applied: Inverse Reactive Current (Negative Reactance) on Phases, Positive Magneto-Reluctive Coupling via Neutral/Ground.
 * Geometry: Logarithmic Spiral Housing generated by winding a mesh into a continuous loop for "Logarithmic Casework".
 */

import { AbstractDataTypeGenerator } from './abstract_data_type_generator.js';
import type { PhaseData, DetractorConfig, CircuitBreakerState } from '../types.ts';

// ==========================================
// CONFIGURATION & CONSTANTS
// ==========================================

const LOGARITHMIC_SPIN_RADIUS = 10.5; // Base radius of the spiral housing
const SPINDULAR_ANGLE_STEP = Math.PI / (LOGARITHMIC_SPIN_RADIUS * 2); // ~34 degrees per turn
const NOISE_AMPLITUDE = 8;       // VOLTAGE noise for stability margin

interface LogarithmicSpool {
    angle: number;           // Degrees of rotation in the spiral housing
    radius: number;          // Distance from center to mesh point
}

class PhaseDetractor implements AbstractDataTypeGenerator {
    private _config?: DetractorConfig;
    
    constructor(config?: DetractorConfig) {
        this._config = config || {};
        
        if (this._config?.phaseWindings === 'neutral') {
            // Grounded Neutral Leg for Synchronism Control
            this.neutralPhaseId = 0; 
        } else {
            // Standard Phase Windings (-j*X) on Phases, Positive coupling via neutral/ground
            this.phaseWindingIds = [1, -2];
            this.neutralPhaseId = 3; // Ground reference for negative reactance magnitude control
            
            if (!this._config?.couplingType || !this._config?.neutralGnd) {
                console.warn('Detractor requires coupling type and neutral ground configuration');
                throw new Error("Configuration missing: 'coupling_type' or 'neutral_gnd'");
            }
        }

        // Initialize state variables for harmonic compensation (Dynamic Impedance Layer)
        this._state = {
            errorMagnitude: 0,           // Magnitude of the phase deviation/error from ideal
            currentPhaseId: null,       // Index tracking which phase is deviating
            targetCurrent: 1.5,         // Target reactive current for synchronization
            harmonicOrder: 2             // Harmonic order to monitor (e.g., 3rd or 4th)
        };

        this._log = [];
    }

    /**
     * Generates the mesh of conductors forming the "Logarithmic Casework" housing.
     * This creates a continuous loop around the logarithmic spiral geometry,
     * simulating the physical casing described in the lore (malleable logarithmic casework).
     */
    private generateConductorMesh(): LogarithmicSpool[] {
        const spools: LogarithmicSpool[] = [];

        for (let angleDeg = 0; angleDeg <= Math.PI * 2; angleDeg += SPINDULAR_ANGLE_STEP) {
            // Calculate radius based on logarithm property of circular spiral
            let r = LOGARITHMIC_SPIN_RADIUS + (angle / (Math.PI * 2)) * (LOGARITHMIC_SPIN_RADIUS - 1);

            spools.push({ angle: angleDeg, radius });
        }

        return spools;
    }

    /**
     * Wraps the mesh into a continuous winding topology.
     * This is achieved by wrapping consecutive `conductor_mesh()` objects together in a single logical loop.
     */
    private wrapIntoContinuousLoop(spoolIndices: number[]): LogarithmicSpool[] {
        const wrapped = [];

        // Group indices to form the spiral path (wrapping points)
        let currentAngleDeg = 0;
        
        for (let i = 1; i < spoolIndices.length; i++) {
            if (spoolIndices[i] !== -2 && !this._config?.neutralGnd) continue; // Skip non-neutral

            const nextIndex = (i + 1) % spoolIndices.length;
            
            let r = LOGARITHMIC_SPIN_RADIUS + ((currentAngleDeg / Math.PI * 2)) * (LOGARITHMIC_SPIN_RADIUS - 1);

            wrapped.push({ angle: currentAngleDeg, radius });
        }

        // Close the loop at index 0 to ensure continuity of the spiral housing
        if (!this._config?.neutralGnd) {
             const
